run:
  go: "1.21"
  timeout: 5m
  skip-dirs:
    - "testdata"
linters:
  enable:
    - bodyclose
    - gochecknoinits
    - gochecknoglobals
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - misspell
    - nestif
    - revive
    - testpackage
    - whitespace
    - wsl
linters-settings:
  revive:
    rules:
      - name: bare-return
      - name: blank-imports
      - name: duplicated-imports
      - name: dot-imports
      - name: superfluous-else
      - name: indent-error-flow
      - name: range
      - name: errorf
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: receiver-naming
      - name: increment-decrement
      - name: unexported-return
      - name: unexported-naming
      - name: time-naming
      - name: var-declaration
      - name: line-length-limit
        arguments: [120]
      - name: unused-parameter
      - name: unused-receiver
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gochecknoglobals
  include:
    - EXC0002
