version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - 8088:8088
    environment:
      - ENVIRONMENT=prod
      - LOG_LEVEL=-10
      - APP_NAME=ports-service
      - APP_VERSION=v0.0.1
      - SERVER_PORT=8088
    networks:
      - ports-public

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
      target: ingestor
    environment:
      - ENVIRONMENT=test
      - LOG_LEVEL=-10
      - APP_NAME=ports-ingestor
      - APP_VERSION=v0.0.1
      - INGESTOR_FILEPATH=/ingest/ports.json
      - INGESTOR_BATCH_SIZE=50
      - SERVER_HOSTNAME=http://server
      - SERVER_PORT=8088
    volumes:
      - ./testdata:/ingest/
    depends_on:
      - server
    networks:
      - ports-public

networks:
  ports-public:
    name: ports-network
    driver: bridge